# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeometryComparator
                                 A QGIS plugin
 Detects changes between two vector layers (Polygon, Line or Point) by comparing features based on a Unique ID field and their geometries, identifying Added, Deleted, and Modified features with high accuracy
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-06-10
        copyright            : (C) 2025 by Anustup Jana
        email                : anustupjana21@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GeometryComparator class from file GeometryComparator.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .geometry_comparator import GeometryComparator
    return GeometryComparator(iface)
